[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[lib]
name = "calculator"
path = "src/lib.rs"

[[bin]]
name = "calc"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.29", default-features = false, features = ["default_fonts", "glow"] }
